/**
 * Mock-exam engine for the Mendix Intermediate Developer certification.
 *
 * IMPORTANT: these are ORIGINAL practice questions written to mirror the real
 * exam's format, topic weighting and difficulty — they are NOT copied from the
 * actual (confidential) certification. Every answer is aligned with the public
 * Mendix documentation (docs.mendix.com). Treat this as realistic practice.
 *
 * Real exam parameters replicated below: 50 questions, 90 minutes, 75% to pass,
 * weighted by the community-reported module blueprint.
 */

export type ExamModule =
  | 'Domain Model'
  | 'Security'
  | 'Pages'
  | 'Microflows'
  | 'Agile'
  | 'XPath'
  | 'Modules'
  | 'Translation'

/** How many questions of each module appear on a 50-question exam. */
export const BLUEPRINT: Record<ExamModule, number> = {
  'Domain Model': 10,
  Security: 8,
  Pages: 7,
  Microflows: 7,
  Agile: 6,
  XPath: 5,
  Modules: 4,
  Translation: 3,
}

export const EXAM = { count: 50, minutes: 90, passPct: 75 }

/** A pool seed: correct answer `a` + three distractors `d`. Options get shuffled at runtime. */
interface Seed {
  m: ExamModule
  q: string
  a: string
  d: [string, string, string]
  why: string
}

const POOL: Seed[] = [
  /* ------------------------------ Domain Model ------------------------------ */
  { m: 'Domain Model', q: 'Which association multiplicities can you model between two entities?', a: 'One-to-one, one-to-many and many-to-many', d: ['Only one-to-many', 'One-to-many and many-to-many only', 'Zero-to-one and many-to-any'], why: 'Multiplicity derives from the association Type (Reference vs Reference set) plus Owner.' },
  { m: 'Domain Model', q: 'What is the difference between a Reference and a Reference set association?', a: 'A Reference points to at most one object on the owner side; a Reference set is many-to-many', d: ['Reference is cross-module only', 'Reference set cannot have delete behavior', 'There is no difference'], why: 'Reference = single-valued end; Reference set = the multi-valued many-to-many end.' },
  { m: 'Domain Model', q: 'In a one-to-many association, where is the reference stored?', a: 'On the "many" side (the owner)', d: ['On the "one" side', 'Always in a separate join table', 'On both entities'], why: 'For 1-* the many side owns the reference; only *-* uses a join table.' },
  { m: 'Domain Model', q: 'How does generalization differ from an association?', a: 'Generalization is an "is-a" (inheritance) relationship; association is a "has-a"/"uses" relationship', d: ['They are the same', 'Association is inheritance; generalization is a foreign key', 'Generalization only works cross-module'], why: 'A specialization inherits from its generalization; an association links independent entities.' },
  { m: 'Domain Model', q: 'A specialization inherits which of these from its generalization?', a: 'Attributes, associations and validation rules, but NOT access rules', d: ['Everything including access rules', 'Only attributes', 'Nothing'], why: 'Members and validation inherit; entity access rules are defined per entity.' },
  { m: 'Domain Model', q: 'Which are the three delete-behavior options on an association?', a: 'Keep the associated objects, delete them as well, or delete only if not associated', d: ['Cascade, restrict, nullify', 'Soft delete, hard delete, archive', 'None — deletes are automatic'], why: 'Delete behavior is keep (default), cascade, or prevent-with-error.' },
  { m: 'Domain Model', q: 'To automatically delete a Customer’s Orders when the Customer is deleted, you set delete behavior to…', a: 'Delete the Order objects as well (cascading delete)', d: ['Keep the Orders', 'Delete only if not associated', 'Nothing is needed'], why: 'Cascading delete propagates to associated objects.' },
  { m: 'Domain Model', q: 'Which delete behavior stops a delete while associated objects still exist?', a: 'Delete only if the object is not associated (prevent, with an error message)', d: ['Cascading delete', 'Keep associated objects', 'Rollback delete'], why: 'Prevent-delete blocks the action and shows a message.' },
  { m: 'Domain Model', q: 'What characterises a non-persistable entity?', a: 'It has no database table and lives in memory during the session', d: ['It is stored in the database like any entity', 'It cannot have attributes', 'It only works offline'], why: 'Non-persistable entities are in-memory only.' },
  { m: 'Domain Model', q: 'Which is a limitation of non-persistable entities?', a: 'You cannot define indexes on them', d: ['They cannot have attributes', 'They cannot appear on pages', 'They cannot be used in microflows'], why: 'No database table means no indexes and no stored validation.' },
  { m: 'Domain Model', q: 'How does an AutoNumber attribute behave?', a: 'It is an auto-incremented whole number generated by the database', d: ['It is a random unique string', 'It is freely editable by the user', 'It only exists on non-persistable entities'], why: 'The database assigns incrementing values; it is a stored attribute.' },
  { m: 'Domain Model', q: 'What does the Enumeration attribute type store?', a: 'A single value from a fixed, predefined list', d: ['Any free text', 'A list of associated objects', 'A binary file'], why: 'Enumerations constrain the value to developer-defined options.' },
  { m: 'Domain Model', q: 'How does a calculated attribute differ from a stored attribute?', a: 'It is recomputed by a microflow on every retrieve and is not stored or sortable', d: ['It is saved in the database like any attribute', 'It can only hold strings', 'It is faster to sort on'], why: 'Calculated attributes run a microflow on read and are not persisted.' },
  { m: 'Domain Model', q: 'What is the effect of adding an index to an attribute?', a: 'Faster retrieval when searched, but slower inserts/updates/deletes; persistable entities only', d: ['It speeds up everything equally', 'It makes the attribute required', 'It encrypts the value'], why: 'Indexes trade faster reads for slower writes.' },
  { m: 'Domain Model', q: 'To store an uploaded image, your entity should generalize from…', a: 'System.Image', d: ['System.FileDocument', 'System.User', 'System.Session'], why: 'System.Image (a FileDocument specialization) adds thumbnail handling.' },
  { m: 'Domain Model', q: 'If two access rules for the same module role apply to an entity, how are they combined?', a: 'Additively — the rights of all applicable rules are combined', d: ['The most restrictive wins', 'Only the first rule applies', 'They cancel out'], why: 'Mendix unions the granted rights across matching rules.' },

  /* --------------------------------- Security -------------------------------- */
  { m: 'Security', q: 'Which are the three application security levels?', a: 'Off, Prototype/Demo, Production', d: ['Low, Medium, High', 'Dev, Test, Live', 'None, Basic, Full'], why: 'These are the only three levels.' },
  { m: 'Security', q: 'At Prototype/Demo security, what is enforced?', a: 'Sign-in, page and microflow access — but all data is accessible', d: ['Full entity/data access', 'Nothing at all', 'Only anonymous access'], why: 'Entity (data) access is only enforced at Production.' },
  { m: 'Security', q: 'The "Off" security level is only allowed for…', a: 'Local testing and Free Apps', d: ['Licensed production nodes', 'Acceptance environments', 'Any deployment'], why: 'With no security enforced, Off cannot be used for licensed production.' },
  { m: 'Security', q: 'Raising security to Production makes which configuration mandatory?', a: 'Entity (data) access rules and dataset access', d: ['Page access', 'Microflow access', 'Sign-in configuration'], why: 'Production adds entity/dataset access on top of page/microflow checks.' },
  { m: 'Security', q: 'How do user roles relate to module roles?', a: 'A user role aggregates one or more module roles; users are assigned only user roles', d: ['They are identical', 'Module roles are assigned directly to users', 'User roles live inside a module'], why: 'User roles bundle module roles, which carry the rights.' },
  { m: 'Security', q: 'Why does Mendix separate module roles from user roles?', a: 'So a module stays self-contained and reusable across apps and the Marketplace', d: ['To make deployment faster', 'Because users must see module roles', 'It is a meaningless legacy split'], why: 'Module roles keep modules independent of the app they live in.' },
  { m: 'Security', q: 'Where do you connect user roles to module roles?', a: 'In App Security (the User roles tab)', d: ['In user settings', 'In module settings', 'In System administration'], why: 'The mapping is configured in App Security.' },
  { m: 'Security', q: 'An entity access rule can define which of these?', a: 'CRUD rights, per-member read/write, and an XPath row constraint', d: ['Only Read', 'Only page navigation', 'Only microflow execution'], why: 'Access rules combine object rights, member rights and an XPath constraint.' },
  { m: 'Security', q: 'What does an XPath constraint on an access rule provide, and where does it work?', a: 'Row-level security; on persistable entities only (it runs against the database)', d: ['Column formatting on any entity', 'Faster page loads', 'Translation of labels'], why: 'It filters which rows a role can access, using the database.' },
  { m: 'Security', q: 'How is attribute-level (member) security configured?', a: 'By setting Read or Read+Write per member in the access rule', d: ['By writing a microflow per attribute', 'It is not possible', 'Only at page level'], why: 'Member checkboxes control read/write per attribute and association.' },
  { m: 'Security', q: 'Which statement about page access is true?', a: 'It is granted per module role; hiding a page does not by itself protect its data', d: ['Restricting a page blocks all access including deep links', 'It is set at user-role level directly', 'All pages are open to all roles at Production'], why: 'Menu/button visibility is controlled by page access, but data needs entity access.' },
  { m: 'Security', q: 'With Production security, how do you allow users without an account?', a: 'Enable anonymous users in App Security and assign a user role', d: ['Set security back to Prototype', 'Give everyone Administrator', 'Disable entity access rules'], why: 'Anonymous access is enabled in App Security with an assigned role.' },
  { m: 'Security', q: 'What are demo users used for?', a: 'One per user role (local/Free App) to test and demo the app as each role', d: ['Real production accounts on all environments', 'Accounts only the Scrum Master uses', 'Public anonymous accounts'], why: 'Demo users let you sign in as each role during development.' },

  /* ---------------------------------- Pages ---------------------------------- */
  { m: 'Pages', q: 'Which widget shows exactly one object?', a: 'Data view', d: ['Data grid', 'List view', 'Template grid'], why: 'A data view is bound to a single object.' },
  { m: 'Pages', q: 'Which widget shows a list where each object uses a custom template?', a: 'List view', d: ['Data grid', 'Data view', 'Reference selector'], why: 'A list view renders each object with a template you build.' },
  { m: 'Pages', q: 'Which widget shows a list in a searchable table of columns?', a: 'Data grid', d: ['List view', 'Data view', 'Snippet'], why: 'A data grid provides columns with search, sort and paging.' },
  { m: 'Pages', q: 'Which data sources can populate a list view?', a: 'Database, association, microflow and nanoflow', d: ['Only database', 'Only microflow', 'Only a REST call'], why: 'Data widgets accept database, association, microflow or nanoflow sources.' },
  { m: 'Pages', q: 'How does a snippet differ from a building block?', a: 'A snippet keeps a live link (edits propagate); a building block is copied onto the page', d: ['They are identical', 'A building block propagates changes', 'Snippets cannot contain widgets'], why: 'Snippets update everywhere; building blocks are copy-once.' },
  { m: 'Pages', q: 'The empty area of a layout that a page fills is called a…', a: 'Placeholder', d: ['Snippet', 'Building block', 'Region'], why: 'Placeholders are the gaps pages fill in a layout.' },
  { m: 'Pages', q: 'When one layout is based on another, the parent is called the…', a: 'Master layout', d: ['Base template', 'Snippet', 'Navigation profile'], why: 'The master layout is the layout another layout is based on.' },
  { m: 'Pages', q: 'How do you show a widget only to certain module roles?', a: 'Use conditional visibility (by module role or expression)', d: ['Only via a microflow', 'Delete it for other users', 'Use a separate app'], why: 'Conditional visibility can target roles or an attribute/expression.' },
  { m: 'Pages', q: 'Which page template helps build a multi-step form with a progress indicator?', a: 'A wizard template', d: ['A data grid template', 'A login template', 'A list template'], why: 'Wizard templates lay out multi-step forms.' },
  { m: 'Pages', q: 'Where do you adjust global colours and fonts without writing CSS?', a: 'The Theme Editor / design properties', d: ['The domain model', 'The navigation document', 'The microflow editor'], why: 'The Theme Editor and design properties apply Atlas styling.' },
  { m: 'Pages', q: 'A user opens a web app on a tablet but no Tablet profile exists. Which profile is used?', a: 'The Responsive profile (the default that cannot be deleted)', d: ['Phone', 'Native mobile', 'None — access is denied'], why: 'Devices fall back to the Responsive profile.' },

  /* -------------------------------- Microflows ------------------------------- */
  { m: 'Microflows', q: 'How many outgoing paths does an exclusive split (decision) follow?', a: 'Exactly one', d: ['Every true path', 'At least one', 'None until a merge'], why: 'Mendix has no inclusive split; a decision follows one path.' },
  { m: 'Microflows', q: 'Which element recombines multiple paths so a shared activity is modelled once?', a: 'A merge', d: ['An exclusive split', 'A loop', 'A continue event'], why: 'A merge joins sequence flows back together.' },
  { m: 'Microflows', q: 'In a loop, the object representing the current element is the…', a: 'Iterator (loop object)', d: ['Parameter', 'Association source', 'Aggregate'], why: 'The iterator is the current list object each pass.' },
  { m: 'Microflows', q: 'Which two events can only be used inside a loop?', a: 'Break and Continue', d: ['Start and End', 'Error and Merge', 'Split and Merge'], why: 'Break exits the loop; Continue skips to the next object.' },
  { m: 'Microflows', q: 'Which aggregate function needs no attribute selected?', a: 'Count', d: ['Sum', 'Average', 'Maximum'], why: 'Count just returns the number of objects.' },
  { m: 'Microflows', q: 'Sum and Average aggregate over which attribute type?', a: 'Numeric (Integer, Long or Decimal)', d: ['String', 'Boolean', 'Enumeration'], why: 'Sum/Average/Min/Max work on numeric values.' },
  { m: 'Microflows', q: 'With "Custom without rollback" error handling, what happens on failure?', a: 'Changes before the error are kept and the error flow is followed', d: ['All changes revert and the flow aborts', 'The error is suppressed silently', 'Only the calling microflow rolls back'], why: 'It keeps prior changes and routes down the error path.' },
  { m: 'Microflows', q: 'With "Custom with rollback" error handling, what happens to changes?', a: 'All changes revert, then the error flow is followed', d: ['They are kept', 'Only the last change reverts', 'Nothing — the flow ends normally'], why: 'It rolls back the scope, then follows the custom error path.' },
  { m: 'Microflows', q: 'To make an open page reflect a changed object, you…', a: 'Commit the object with Refresh in client set to Yes', d: ['Do nothing — it updates automatically', 'Delete and recreate it', 'Restart the app'], why: 'Commit persists it; refresh-in-client pushes it to the page.' },
  { m: 'Microflows', q: 'True or false: retrieving "by association" always avoids a database query.', a: 'False — if the object is not in memory it is still fetched from the database', d: ['True — associations never hit the database', 'True — but only in nanoflows', 'False — associations cannot be retrieved'], why: 'Association retrieves only skip the DB when the object is already loaded.' },
  { m: 'Microflows', q: 'Which activity fetches data from an external REST API?', a: 'Call REST service', d: ['Retrieve object', 'Export mapping', 'Show page'], why: 'Call REST service performs the outbound request; an import mapping parses the response.' },
  { m: 'Microflows', q: 'What is the role of an import mapping vs an export mapping?', a: 'Import turns incoming JSON/XML into objects; export serialises objects into JSON/XML', d: ['Import turns objects into JSON; export turns JSON into objects', 'Both turn objects into JSON', 'Both are only for CSV'], why: 'Import = data in to objects; export = objects out to JSON/XML.' },

  /* ---------------------------------- Agile ---------------------------------- */
  { m: 'Agile', q: 'In Mendix, developers on a Scrum team are called…', a: 'Business Engineers', d: ['Coders', 'Analysts', 'Architects'], why: 'Mendix labels its app developers Business Engineers.' },
  { m: 'Agile', q: 'What is the Scrum Master primarily responsible for?', a: 'Facilitating the process and removing impediments', d: ['Prioritising the backlog', 'Writing all the microflows', 'Approving the production deployment'], why: 'The Scrum Master serves the team and clears blockers.' },
  { m: 'Agile', q: 'What is the Product Owner primarily responsible for?', a: 'Translating business needs into backlog items and prioritising the backlog', d: ['Removing team blockers', 'Running the standup as a status meeting', 'Merging branches'], why: 'The Product Owner owns and prioritises the backlog.' },
  { m: 'Agile', q: 'How should items in the product backlog be ordered?', a: 'Top to bottom by descending priority', d: ['Alphabetically', 'Oldest first', 'Randomly'], why: 'The backlog is a prioritised list, highest-priority first.' },
  { m: 'Agile', q: 'What do story points estimate?', a: 'Complexity/effort (often on a Fibonacci scale)', d: ['Exact hours', 'Number of developers', 'The story’s priority'], why: 'Story points are a relative estimate of complexity, not hours.' },
  { m: 'Agile', q: 'What does the Team Server provide?', a: 'Built-in Git version control (history, branches, merging, rollback)', d: ['A production database', 'Only screenshot storage', 'Translation services'], why: 'Team Server is the built-in version control for the app model.' },
  { m: 'Agile', q: 'Which merge option merges an entire branch into the main line?', a: '"Merge feature branch" (available on the main line)', d: ['"Advanced merge"', '"Port fix"', '"Revert"'], why: 'Merge feature branch folds a whole branch into main; advanced merge cherry-picks.' },
  { m: 'Agile', q: 'What is a "tagged version" in the Team Server?', a: 'A revision that was used to build a deployment package', d: ['Any Friday commit', 'A deleted branch', 'A comment on a story'], why: 'Building a package tags the underlying revision.' },
  { m: 'Agile', q: 'What are the standard environments on a licensed Mendix Cloud node?', a: 'Test, Acceptance and Production', d: ['Sandbox only', 'Dev and Live only', 'Local, Team Server and Marketplace'], why: 'Licensed nodes provide a Test → Acceptance → Production pipeline.' },

  /* ---------------------------------- XPath ---------------------------------- */
  { m: 'XPath', q: 'Which token represents the currently logged-in user?', a: '[%CurrentUser%]', d: ['[%CurrentObject%]', '[%CurrentDateTime%]', '[%UserRole%]'], why: 'It resolves to the logged-in user’s GUID.' },
  { m: 'XPath', q: 'Which XPath returns the current user’s own submitted requests?', a: "[Module.Request_Submitter = '[%CurrentUser%]']", d: ['[Submitter != CurrentUser]', "[%CurrentUser%] = Submitter", "[Status = 'Open']"], why: 'It compares the Submitter association to the current-user token.' },
  { m: 'XPath', q: 'How do you constrain on an associated entity’s attribute?', a: 'Traverse the association with forward slashes (association/entity/attribute)', d: ['You cannot reference associations', 'Use SQL joins', 'Use a microflow only'], why: 'XPath follows associations with "/".' },
  { m: 'XPath', q: 'Which keyword matches attributes that have no value?', a: 'empty', d: ['null', 'blank', 'none'], why: 'The empty keyword matches members with no value.' },
  { m: 'XPath', q: 'What do contains() and starts-with() do?', a: 'Test whether a string contains, or begins with, a given substring', d: ['Compare numbers only', 'Check associations and enumerations', 'Only work in OQL'], why: 'They are string constraint functions for substring matching.' },
  { m: 'XPath', q: 'What do [%CurrentUser%] and [%CurrentObject%] evaluate to?', a: 'The GUID of the logged-in user, and the GUID of the active object', d: ['The username and object name strings', 'Both the current session', 'One only works on pages'], why: 'Both are system variables resolving to object GUIDs.' },
  { m: 'XPath', q: 'Which expresses a logical AND between two constraints on the same entity?', a: 'Chained brackets [a][b] (equivalent to using "and")', d: ['[a or b]', '[a] / [b]', 'You cannot AND constraints'], why: 'Adjacent bracket constraints are implicitly AND-ed.' },
  { m: 'XPath', q: 'Where can XPath constraints be applied?', a: 'Access rules, microflow/data-source retrieves and page data sources', d: ['Only in access rules', 'Only on pages', 'Only in the Marketplace'], why: 'XPath filters data in access rules, retrieves and page data sources.' },

  /* --------------------------------- Modules --------------------------------- */
  { m: 'Modules', q: 'A Mendix module can contain which of the following?', a: 'A domain model, pages, microflows, module roles and resources', d: ['Only pages', 'Only microflows', 'Only the domain model'], why: 'A module bundles data, documents and its own module roles.' },
  { m: 'Modules', q: 'Where do downloaded Marketplace modules appear?', a: 'Under the "Marketplace modules" folder, behaving like your own modules', d: ['In the System module', 'In a hidden temp folder', 'Merged into your main module'], why: 'They live in the Marketplace-modules folder.' },
  { m: 'Modules', q: 'After importing a module with its own module roles (Prototype/Production), you must…', a: 'Map its module roles to your user roles in App Security', d: ['Do nothing', 'Delete your user roles', 'Set security to Off'], why: 'Every module role must be mapped to a user role to take effect.' },
  { m: 'Modules', q: 'Module roles grant access to which of these?', a: 'Pages, microflows and entities (and members) in that module', d: ['Only entities', 'Only Marketplace content', 'Only navigation items'], why: 'All in-module security is granted per module role.' },
  { m: 'Modules', q: 'How do you reuse a module you built in another app?', a: 'Export the module package and import it into the other app', d: ['Copy the database', 'Retype it', 'Use anonymous users'], why: 'Modules export as a package for import elsewhere.' },
  { m: 'Modules', q: 'What does referencing another module’s entity create?', a: 'A dependency between the modules that must be managed', d: ['Nothing', 'A deletion of the other module', 'Disabled security'], why: 'Cross-module references couple modules; keep them clean.' },

  /* -------------------------------- Translation ------------------------------ */
  { m: 'Translation', q: 'Which feature shows the complete list of translatable texts for a source and destination language?', a: 'Batch translate', d: ['System texts', 'Language selector', 'The domain model'], why: 'Batch translate lists every translatable text side by side.' },
  { m: 'Translation', q: 'What is the default language used for, and what is its initial value?', a: 'It is the fallback when a text is untranslated; initially English (US)', d: ['Only used in Studio Pro; initially Dutch', 'The anonymous user’s language', 'It disables other languages'], why: 'The default language is the fallback, starting as English (US).' },
  { m: 'Translation', q: 'How can an end user switch the app language at runtime?', a: 'With the Language Selector widget', d: ['By reinstalling the app', 'By editing the domain model', 'They cannot'], why: 'The Language Selector switches among enabled languages.' },
  { m: 'Translation', q: 'Where do you add a new language to an app?', a: 'Language Settings (App Settings)', d: ['App Security', 'The domain model', 'Navigation'], why: 'Languages are managed under Language Settings.' },
  { m: 'Translation', q: 'What are "system texts"?', a: 'Standard built-in UI messages you can translate per language', d: ['User-entered data in entities', 'The names of module roles', 'Log file entries'], why: 'System texts are the platform’s standard UI strings; missing ones fall back to the default language.' },
]

export interface ExamQuestion {
  m: ExamModule
  q: string
  options: string[]
  correct: number
  why: string
}

function shuffle<T>(arr: T[]): T[] {
  const a = arr.slice()
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

function build(seed: Seed): ExamQuestion {
  const options = shuffle([seed.a, ...seed.d])
  return { m: seed.m, q: seed.q, options, correct: options.indexOf(seed.a), why: seed.why }
}

/** Generate a fresh, blueprint-weighted 50-question exam with shuffled options. */
export function generateExam(): ExamQuestion[] {
  const chosen: Seed[] = []
  const used = new Set<Seed>()
  ;(Object.keys(BLUEPRINT) as ExamModule[]).forEach((mod) => {
    const pool = shuffle(POOL.filter((s) => s.m === mod))
    const take = pool.slice(0, BLUEPRINT[mod])
    take.forEach((s) => used.add(s))
    chosen.push(...take)
  })
  // top up if any module pool was short of its blueprint count
  if (chosen.length < EXAM.count) {
    const rest = shuffle(POOL.filter((s) => !used.has(s)))
    chosen.push(...rest.slice(0, EXAM.count - chosen.length))
  }
  return shuffle(chosen).slice(0, EXAM.count).map(build)
}

export function poolCount(): number {
  return POOL.length
}

/** All exam questions as ready-to-render quiz questions (options shuffled). */
export function allExamQuestions(): ExamQuestion[] {
  return POOL.map(build)
}
